apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app2
labels:
  - pairs:
      app.kubernetes.io/part-of: platform
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - deployment.yaml
  - service.yaml
  - serviceexport.yaml
  - hpa.yaml
  - pdb.yaml
  - podmonitoring.yaml
  - networkpolicy.yaml
