apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.appName }}
  labels:
    app.kubernetes.io/part-of: platform
  annotations:
    iam.gke.io/gcp-service-account: wl-{{ .Values.appName }}@{{ .Values.projectID }}.iam.gserviceaccount.com
automountServiceAccountToken: false