apiVersion: v1
kind: ServiceAccount
metadata:
  name: app1
  annotations:
    # Workload Identity: this KSA acts as the Google SA below (binding created by Terraform)
    iam.gke.io/gcp-service-account: wl-app1@PROJECT_ID.iam.gserviceaccount.com
automountServiceAccountToken: false
